# Generated by Django 3.1.3 on 2020-11-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangowebauthn', '0002_webauthnprofile_webauthn_ukey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webauthnprofile',
            name='credential_id',
            field=models.CharField(max_length=200),
        ),
    ]
